apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Tell Kustomize to set the namespace for all resources
namespace: dev-namespace

resources:
  - namespace.yaml

# Define the global path to your charts folder here
helmGlobals:
  chartHome: ../../charts

helmCharts:
  - name: demo-nextjs
    releaseName: demo-nextjs-dev
    namespace: dev-namespace
    valuesFile: values-dev.yaml
