apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod-namespace

resources:
  - namespace.yaml

helmGlobals:
  chartHome: ../../charts

helmCharts:
  - name: demo-nextjs
    releaseName: demo-nextjs-prod
    namespace: prod-namespace
    valuesFile: values-prod.yaml
