apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod-namespace

helmCharts:
  - name: demo-nextjs
    releaseName: demo-nextjs-prod
    path: ../../charts/demo-nextjs
    valuesFile: values-prod.yaml
