apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "demo-nextjs.configmapName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "demo-nextjs.labels" . | nindent 4 }}
data:
  NODE_ENV: {{ .Values.env.nodeEnv | quote }}
  PORT: {{ .Values.env.port | quote }}
  LOG_LEVEL: {{ .Values.env.logLevel | quote }}

  NEXT_PUBLIC_APP_NAME: {{ .Values.env.appName | quote }}
  NEXT_PUBLIC_APP_URL: {{ .Values.env.appUrl | quote }}

  OTEL_SERVICE_NAME: {{ .Values.otel.serviceName | quote }}
  OTEL_SERVICE_VERSION: {{ .Values.otel.serviceVersion | quote }}

  OTEL_EXPORTER_OTLP_ENDPOINT: {{ .Values.otel.endpoint | quote }}
  OTEL_EXPORTER_OTLP_PROTOCOL: {{ .Values.otel.protocol | quote }}

  OTEL_TRACES_EXPORTER: {{ .Values.otel.tracesExporter | quote }}
  OTEL_METRICS_EXPORTER: {{ .Values.otel.metricsExporter | quote }}
  OTEL_LOGS_EXPORTER: {{ .Values.otel.logsExporter | quote }}

  NEXT_TELEMETRY_DISABLED: {{ .Values.next.telemetryDisabled | quote }}