apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "demo-nextjs.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "demo-nextjs.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      {{- include "demo-nextjs.selectorLabels" . | nindent 6 }}

  template:
    metadata:
      labels:
        {{- include "demo-nextjs.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "demo-nextjs.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          ports:
            - name: http
              containerPort: {{ .Values.containerPort | default 3000 }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "demo-nextjs.fullname" . }}
            - secretRef:
                name: {{ include "demo-nextjs.fullname" . }}
          readinessProbe:
            httpGet:
              path: {{ .Values.health.readinessPath }}
              port: http

            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3

          livenessProbe:

            httpGet:
              path: {{ .Values.health.livenessPath }}
              port: http

            initialDelaySeconds: 20
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 3

          startupProbe:

            httpGet:
              path: {{ .Values.health.startupPath }}
              port: http

            periodSeconds: 5
            failureThreshold: 30

          resources:
            {{- toYaml .Values.resources | nindent 12 }}

      terminationGracePeriodSeconds: 30