apiVersion: v1
kind: Secret
metadata:
  name: {{ include "demo-nextjs.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "demo-nextjs.labels" . | nindent 4 }}
type: Opaque
stringData:

  ##############################################
  # Database
  ##############################################

  DATABASE_URL: {{ .Values.secret.databaseUrl | quote }}

  ##############################################
  # Authentication
  ##############################################

  AUTH_SECRET: {{ .Values.secret.authSecret | quote }}

  ##############################################
  # JWT
  ##############################################

  JWT_SECRET: {{ .Values.secret.jwtSecret | quote }}

  ##############################################
  # Future API Keys
  ##############################################

  OPENAI_API_KEY: {{ .Values.secret.openaiApiKey | quote }}